config/routes.rb
Rails.application.routes.draw do
  
  get 'stories/index'

  get 'stories/new'

  get 'stories/edit'

  get 'stories/update'

  get 'stories/destroy'

  root 'homepages#home'
#  root 'user#index'

  get 'user/index'

  get 'user/new'

  get 'user/edit'

  get 'user/show'

  get 'user/delete'

  devise_for :users
  

  resources :homepages
  resources :helps
  resources :fans
  resources :codeworks
  resources :users
  resources :stories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fan.rb
class Fan < ApplicationRecord
end

app/controllers/fans_controller.rb
class FansController < ApplicationController
  before_action :set_fan, only: [:show, :edit, :update, :destroy]
  
  def index
    @fans = Fan.all
  end

  def show
  end

  def new
    @fan = Fan.new
    @help = Help.new
    @codework = Codework.new

    @fans = Fan.all
  end

  def edit
  end

  def create
    @fan = Fan.new(fan_params)

    respond_to do |format|
      if @fan.save
        format.html { redirect_to root_path }
        format.js 
      else
        format.html { render :new }
        format.js 
      end
    end
  end

  def update
    respond_to do |format|
      if @fan.update(fan_params)
        format.html { redirect_to @fan, notice: 'Fan was successfully updated.' }
        format.json { render :show, status: :ok, location: @fan }
      else
        format.html { render :edit }
        format.json { render json: @fan.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @fan.destroy
    respond_to do |format|
      format.html { redirect_to fans_url, notice: 'Fan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_fan
      @fan = Fan.find(params[:id])
    end

    def fan_params
      params.require(:fan).permit(:name, :country, :book, :comment, :rating)
    end
end

app/helpers/fans_helper.rb
module FansHelper
end

app/views/fans/_fans.html.erb
<% if @fan.name != nil %>
	<li id="<%= @fan.id %>">
	    <p> name: <%= @fan.name %> </p>
	   	<p> comment: <%= @fan.comment %> </p>
	</li>

	<% else %>
<% end %>

app/views/fans/_form.html.erb
<%= form_with(model: @fan, local: false,) do |form| %>
  <% if @fan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fan.errors.count, "error") %> prohibited this fan from being saved:</h2>

      <ul>
      <% fan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :fan_name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :fan_country %>
  </div>

  <div class="field">
    <%= form.label :book %>
    <%= form.text_field :book, id: :fan_book %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :fan_comment %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :fan_rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fans/_test1.html.erb
<ul>
	<% @fans.each do |fan| %>
		<li>	
			<p>name: <%= fan.name %></p>
			<p>comment: <%= fan.comment %></p>
		</li>
	<% end %>
	<%= render partial: 'fans/fans', locals: { fan: @fan } %>
</ul>

app/views/fans/create.js.erb
alert('hi, we did it');

$('ul').append("<%= j render partial: 'fans', locals: {fan: @fan} %>");

app/views/fans/edit.html.erb
<h1>Editing Fan</h1>

<%= render 'form', fan: @fan %>

<%= link_to 'Show', @fan %> |
<%= link_to 'Back', fans_path %>

app/views/fans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>Book</th>
      <th>Comment</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fans.each do |fan| %>
      <tr>
        <td><%= fan.name %></td>
        <td><%= fan.country %></td>
        <td><%= fan.book %></td>
        <td><%= fan.comment %></td>
        <td><%= fan.rating %></td>
        <td><%= link_to 'Show', fan %></td>
        <td><%= link_to 'Edit', edit_fan_path(fan) %></td>
        <td><%= link_to 'Destroy', fan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fan', new_fan_path %>

app/views/fans/new.html.erb
<h1>New Fan</h1>

<%= render partial: 'fans/form', :fan => @fan %>

<%= render partial: 'helps/form', :help => @help %>

<%= render partial: 'codeworks/form', :codework => @codework %>

<%= link_to 'Back', fans_path %>

app/views/fans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fan.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @fan.country %>
</p>

<p>
  <strong>Book:</strong>
  <%= @fan.book %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @fan.comment %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @fan.rating %>
</p>

<%= link_to 'Edit', edit_fan_path(@fan) %> |
<%= link_to 'Back', fans_path %>