config/routes.rb
Rails.application.routes.draw do
  
  get 'stories/index'

  get 'stories/new'

  get 'stories/edit'

  get 'stories/update'

  get 'stories/destroy'

  root 'homepages#home'
#  root 'user#index'

  get 'user/index'

  get 'user/new'

  get 'user/edit'

  get 'user/show'

  get 'user/delete'

  devise_for :users
  

  resources :homepages
  resources :helps
  resources :fans
  resources :codeworks
  resources :users
  resources :stories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/help.rb
class Help < ApplicationRecord
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  before_action :set_help, only: [:show, :edit, :update, :destroy]


  def index
    @helps = Help.all
  end

  def show
  end

  def new
    @help = Help.new
  end
  
  def edit
  end

  def create
    @help = Help.new(help_params)

    respond_to do |format|
      if @help.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @help }
      else
        format.html { render :new }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @help.update(help_params)
        format.html { redirect_to @help, notice: 'Help was successfully updated.' }
        format.json { render :show, status: :ok, location: @help }
      else
        format.html { render :edit }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @help.destroy
    respond_to do |format|
      format.html { redirect_to helps_url, notice: 'Help was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_help
      @help = Help.find(params[:id])
    end

    def help_params
      params.require(:help).permit(:genre, :task, :country, :timeframe, :comments)
    end
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/views/helps/_form.html.erb
<%= form_with(model: @help, local: true) do |form| %>
  <% if @help.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(help.errors.count, "error") %> prohibited this help from being saved:</h2>

      <ul>
      <% help.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre, id: :help_genre %>
  </div>

  <div class="field">
    <%= form.label :task %>
    <%= form.text_field :task, id: :help_task %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :help_country %>
  </div>

  <div class="field">
    <%= form.label :timeframe %>
    <%= form.text_field :timeframe, id: :help_timeframe %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments, id: :help_comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/helps/create.js.erb
create.js.erb

app/views/helps/edit.html.erb
<h1>Editing Help</h1>

<%= render 'form', help: @help %>

<%= link_to 'Show', @help %> |
<%= link_to 'Back', helps_path %>

app/views/helps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Helps</h1>

<table>
  <thead>
    <tr>
      <th>Genre</th>
      <th>Task</th>
      <th>Country</th>
      <th>Timeframe</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @helps.each do |help| %>
      <tr>
        <td><%= help.genre %></td>
        <td><%= help.task %></td>
        <td><%= help.country %></td>
        <td><%= help.timeframe %></td>
        <td><%= help.comments %></td>
        <td><%= link_to 'Show', help %></td>
        <td><%= link_to 'Edit', edit_help_path(help) %></td>
        <td><%= link_to 'Destroy', help, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Help', new_help_path %>

app/views/helps/new.html.erb
<h1>New Help</h1>

<%= render 'form', help: @help %>

<%= link_to 'Back', helps_path %>

app/views/helps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Genre:</strong>
  <%= @help.genre %>
</p>

<p>
  <strong>Task:</strong>
  <%= @help.task %>
</p>

<p>
  <strong>Country:</strong>
  <%= @help.country %>
</p>

<p>
  <strong>Timeframe:</strong>
  <%= @help.timeframe %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @help.comments %>
</p>

<%= link_to 'Edit', edit_help_path(@help) %> |
<%= link_to 'Back', helps_path %>