config/routes.rb
Rails.application.routes.draw do
  
  get 'stories/index'

  get 'stories/new'

  get 'stories/edit'

  get 'stories/update'

  get 'stories/destroy'

  root 'homepages#home'
#  root 'user#index'

  get 'user/index'

  get 'user/new'

  get 'user/edit'

  get 'user/show'

  get 'user/delete'

  devise_for :users
  

  resources :homepages
  resources :helps
  resources :fans
  resources :codeworks
  resources :users
  resources :stories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/codework.rb
class Codework < ApplicationRecord
end

app/controllers/codeworks_controller.rb
class CodeworksController < ApplicationController
  before_action :set_codework, only: [:show, :edit, :update, :destroy]

  def index
    @codeworks = Codework.all
  end

  def show
  end

  def new
    @codework = Codework.new
  end

  def edit
  end

  def create
    @codework = Codework.new(codework_params)

    respond_to do |format|
      if @codework.save
        format.html { redirect_to root_path, notice: 'Codework was successfully created.' }
        format.json { render :show, status: :created, location: @codework }
      else
        format.html { render :new }
        format.json { render json: @codework.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @codework.update(codework_params)
        format.html { redirect_to @codework, notice: 'Codework was successfully updated.' }
        format.json { render :show, status: :ok, location: @codework }
      else
        format.html { render :edit }
        format.json { render json: @codework.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @codework.destroy
    respond_to do |format|
      format.html { redirect_to codeworks_url, notice: 'Codework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_codework
      @codework = Codework.find(params[:id])
    end


    def codework_params
      params.require(:codework).permit(:company, :city, :state, :postion, :salary, :comments)
    end
end

app/helpers/codeworks_helper.rb
module CodeworksHelper
end

app/views/codeworks/_form.html.erb
<%= form_with(model: @codework, local: true) do |form| %>
  <% if @codework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(codework.errors.count, "error") %> prohibited this codework from being saved:</h2>

      <ul>
      <% codework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, id: :codework_company %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :codework_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :codework_state %>
  </div>

  <div class="field">
    <%= form.label :postion %>
    <%= form.text_field :postion, id: :codework_postion %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.number_field :salary, id: :codework_salary %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments, id: :codework_comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/codeworks/create.js.erb
create.js.erb

app/views/codeworks/edit.html.erb
<h1>Editing Codework</h1>

<%= render 'form', codework: @codework %>

<%= link_to 'Show', @codework %> |
<%= link_to 'Back', codeworks_path %>

app/views/codeworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Codeworks</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>City</th>
      <th>State</th>
      <th>Postion</th>
      <th>Salary</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @codeworks.each do |codework| %>
      <tr>
        <td><%= codework.company %></td>
        <td><%= codework.city %></td>
        <td><%= codework.state %></td>
        <td><%= codework.postion %></td>
        <td><%= codework.salary %></td>
        <td><%= codework.comments %></td>
        <td><%= link_to 'Show', codework %></td>
        <td><%= link_to 'Edit', edit_codework_path(codework) %></td>
        <td><%= link_to 'Destroy', codework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Codework', new_codework_path %>

app/views/codeworks/new.html.erb
<h1>New Codework</h1>

<%= render 'form', codework: @codework %>

<%= link_to 'Back', codeworks_path %>

app/views/codeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @codework.company %>
</p>

<p>
  <strong>City:</strong>
  <%= @codework.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @codework.state %>
</p>

<p>
  <strong>Postion:</strong>
  <%= @codework.postion %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @codework.salary %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @codework.comments %>
</p>

<%= link_to 'Edit', edit_codework_path(@codework) %> |
<%= link_to 'Back', codeworks_path %>