config/routes.rb
Rails.application.routes.draw do
  
  get 'stories/index'

  get 'stories/new'

  get 'stories/edit'

  get 'stories/update'

  get 'stories/destroy'

  root 'homepages#home'
#  root 'user#index'

  get 'user/index'

  get 'user/new'

  get 'user/edit'

  get 'user/show'

  get 'user/delete'

  devise_for :users
  

  resources :homepages
  resources :helps
  resources :fans
  resources :codeworks
  resources :users
  resources :stories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

    validates :username, presence: true, uniqueness: true


  # has_one_attached :avatar

  has_many :comments


end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :edit, :update, :destroy]


  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path }
#        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
#        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
#        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
#        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
#      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :username, :email, :location, :avatar, :password)
    end 
   
    def resource_name
      :user
    end
    helper_method :resource_name
   
    def resource
      @resource ||= User.new
    end
    helper_method :resource
   
    def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
    end
    helper_method :devise_mapping
   
    def resource_class
      User
    end
    helper_method :resource_class
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_new2.html.erb
<%= form_for(:user, :url => session_path(:user)) do |f| %>
  <p>Email: <%= f.text_field :email %></p>
  <p>Password: <%= f.password_field :password %></p>
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %>
  <%= f.submit 'Sign in' %>
  <%= link_to "Forgot your password?", new_password_path(:user) %>
<% end %>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

<div class="modal-body" id="new_user_form">
        <h2>Sign Up</h2>
        <%= form_with(model: @user, local: true) do |form| %>
          <% if @user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(user.errors.count, "error") %> prohibited this help from being saved:</h2>

              <ul>
              <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= form.label :name %>
            <%= form.text_field :name, id: :user_name %>
          </div>

          <div class="field">
            <%= form.label :username %>
            <%= form.text_field :username, id: :user_username %>
          </div>

          <div class="field">
            <%= form.label :email %>
            <%= form.text_field :email, id: :user_email %>
          </div>

          <div class="field">
            <%= form.label :location %>
            <%= form.text_field :location, id: :user_location %>
          </div>

          <div class="field">
            <%= form.label :password %>
            <%= form.text_field :password, id: :user_password %>
          </div>

          <div class="actions">
            <%= form.submit %>
          </div>
        <% end %>
</div>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>